Design turret audio
Org-Be-Nandesuka/FocusBreakout pull request #8
Opened 2022-01-01 06:47 UTC by Charles-Huang-Y4

2022-01-01 06:48 UTC, Charles-Huang-Y4 commented
hi

2022-01-03 06:57 UTC, AlexisCM requested changes

2022-01-03 06:57 UTC, AlexisCM commented on Assets/Scripts/Player/Player.cs
>                  throw new ArgumentException("Speed must be at least 0.");
Update message to match  `if` check

2022-01-03 07:01 UTC, AlexisCM approved these changes
LGTM~

2022-01-03 07:01 UTC, merged